name: GoogleTests_template

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install gtest manually
      run: sudo apt-get install libgtest-dev && cd /usr/src/gtest && sudo cmake CMakeLists.txt && sudo make && sudo ln -s /usr/lib/libgtest.a /usr/local/lib/libgtest.a && sudo ln -s /usr/lib/libgtest_main.a /usr/local/lib/libgtest_main.a
    - uses: actions/checkout@v1
    - name: configure
      run: cd /home/runner/work/githubActionsGoogleTest/githubActionsGoogleTest/tests && mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS="-Werror" ..
    - name: make
      run: run: cd /home/runner/work/githubActionsGoogleTest/githubActionsGoogleTest/tests && cd build && make
    - name: ls
      run: cd /home/runner/work/githubActionsGoogleTest/githubActionsGoogleTest && ls
    - name: ls2
      run: cd /home/runner/work/githubActionsGoogleTest/githubActionsGoogleTest/tests && ls
    - name: ls3
      run: cd /home/runner/work/githubActionsGoogleTest/githubActionsGoogleTest/build && ls
    - name: Run Test
      run: /home/runner/work/githubActionsGoogleTest/githubActionsGoogleTest/tests/build/test_module
